### ISSUE TITLE
Hardcoded compiler name in Makefile??

### ISSUE THREAD

**Issue by andi8086** [frank-w/bpi-r2-uboot#1]
Please please - the compiler has to be settable with CROSS_COMPILE_ prefix, not being hardcoded in the makefile or so. This is really bad. There are standards that should be honored.

➜  bpi-r2-uboot git:(master) ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make mt7623_evb_config
Configuring for mt7623_evb board...

➜  bpi-r2-uboot git:(master) ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make                  
make: /opt/buildroot-gcc463_arm/usr/bin/arm-buildroot-linux-uclibcgnueabi-gcc: Command not found
/bin/sh: /opt/buildroot-gcc463_arm/usr/bin/arm-buildroot-linux-uclibcgnueabi-gcc: No such file or directory
dirname: missing operand
Try 'dirname --help' for more information.
  GEN     include/autoconf.mk.dep
/bin/sh: /opt/buildroot-gcc463_arm/usr/bin/arm-buildroot-linux-uclibcgnueabi-gcc: No such file or directory
  GEN     include/autoconf.mk
/bin/sh: /opt/buildroot-gcc463_arm/usr/bin/arm-buildroot-linux-uclibcgnueabi-gcc: No such file or directory
  CHK     include/config/uboot.release
  UPD     include/config/uboot.release
  CHK     include/generated/version_autogenerated.h
/bin/sh: /opt/buildroot-gcc463_arm/usr/bin/arm-buildroot-linux-uclibcgnueabi-gcc: No such file or directory
/bin/sh: /opt/buildroot-gcc463_arm/usr/bin/arm-buildroot-linux-uclibcgnueabi-ld: No such file or directory
  UPD     include/generated/version_autogenerated.h
  CHK     include/generated/timestamp_autogenerated.h
  UPD     include/generated/timestamp_autogenerated.h
  HOSTCC  scripts/basic/fixdep
  CC      lib/asm-offsets.s
/bin/sh: /opt/buildroot-gcc463_arm/usr/bin/arm-buildroot-linux-uclibcgnueabi-gcc: No such file or directory
make[1]: *** [/home/projects/bpi-r2-uboot/./Kbuild:35: lib/asm-offsets.s] Error 127
make: *** [Makefile:1040: prepare0] Error 2

**Comment by andi8086** [comment]
I created a merge-request for this one. Maybe you need to adapt some of your build-scripts.

**Comment by frank-w** [comment]
merged Pull-request,

CROSS_COMPILE-override is inherited from official repo

https://github.com/BPI-SINOVOIP/BPI-R2-bsp/blob/d94f55022a9192cb181d380b1a6699949a36f30c/u-boot-mt/Makefile#L208
